#:kivy 1.10.1

<MyScreenManager>:
    id: _my_screen_manager
    LoginScreen:
        id: _login_screen
        name: 'LoginScreen'
        manager: _my_screen_manager
    MainScreen:
        id: _main_screen
        name: 'MainScreen'
        manager: _my_screen_manager
        login_screen: _login_screen
    SearchResultsScreen:
        id: _search_results_screen
        name: 'SearchResultsScreen'
        manager: _my_screen_manager
    
